# Dockerfile.streamlit
FROM python:3.12-slim

WORKDIR /opt/streamlit/app

# Install dependencies
COPY streamlit/requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "app.py", \
     "--server.port=8501", \
     "--server.address=0.0.0.0", \
     "--server.headless=true"]